### ISSUE TITLE
Create superuser account

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/DevOps#3]
Create a superuser account so I am able to log into our Django admin. DM me the credentials afterwards.

https://api.thenewboston.com/admin/login/?next=/admin/

**Comment by shashanksinha89** [comment]
@vosi should we generate credentials during startup process. Thoughts ?

https://stackoverflow.com/questions/28959063/create-django-superuser-on-aws-elastic-beanstalk/31645228

**Comment by shashanksinha89** [comment]
credentials shared in DM.

**Comment by ThaDeveloper** [comment]
> @vosi should we generate credentials during startup process. Thoughts ?
> 
> https://stackoverflow.com/questions/28959063/create-django-superuser-on-aws-elastic-beanstalk/31645228

I think this is the standard way
