### ISSUE TITLE
Implement github action for backend

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/DevOps#4]
You need to Implement github action for backend as per @buckyroberts  instructions.

If you have any issue in this, you can contact Greg or me on Discord.

**Comment by Ankit-Singla** [comment]
Hi

I would like to contribute to address this issue. Are you welcoming open source contributions? If yes, where can I know more about contributing to the project?

**Comment by ma2b0043** [comment]
> Hi
> 
> I would like to contribute to address this issue. Are you welcoming open source contributions? If yes, where can I know more about contributing to the project?

@Ankit-Singla we do welcome open source contributions, only the task with `bounty` assigned to them are eligible for anyone to complete, other than that the person assigned to task has to complete it. May I ask are you on our Discord group? If not you can join us using this link: https://discord.com/invite/thenewboston
In our community we have alot of open source projects which can use people like you to contribute to the projects being built. If you need any more information you can ask me on discord(I'm under this username: Muhammad Anas Azam Bhatti#3383).
