### ISSUE TITLE
Linting workflows

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/DevOps#5]
Create GitHub workflows to check for linting issues similar to https://github.com/thenewboston-developers/Website/blob/development/.github/workflows/linting.yml when a new PR is created on any of the following repos:

- https://github.com/thenewboston-developers/Account-Manager
- https://github.com/thenewboston-developers/thenewboston-js
- https://github.com/thenewboston-developers/utils-js
- https://github.com/thenewboston-developers/ui-js

**Comment by angle943** [comment]
note, `thenewboston-js` might not have a lint library. if it doesn't, you can skip that one

**Comment by shashanksinha89** [comment]
added lint checks.
