### ISSUE TITLE
Take down testnet nodes

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/DevOps#8]
We no longer need to testnet. We can take down all testnet nodes/instances. We are currently making some large updates so will be deploying updated nodes for the betanet.

**Comment by shashanksinha89** [comment]
Stopped relevant nodes. I will remove them in some time.

![Screen Shot 2021-02-15 at 1 05 05 PM](https://user-images.githubusercontent.com/13620565/107925965-90c80980-6f8e-11eb-975d-62faacb78e8a.png)
